# Generated by Django 4.0.1 on 2022-03-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-last_name']},
        ),
    ]
