# Generated by Django 4.0.1 on 2022-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='pics')),
                ('date_of_birth', models.DateTimeField()),
                ('amount_owed', models.FloatField()),
                ('graduated', models.BooleanField(default=False)),
            ],
        ),
    ]
